# Generated by Django 4.0.5 on 2022-08-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=256)),
            ],
        ),
    ]
